let step3InputsArray: {
  key: string;
  input_id: number;
  input_type: number; //0== textfield, 1 == combobox, 2==upload ,  3 == double input(combobox + textfield), 4===double download, 5=== triple download, 6===sixtuple download
  upper_text: string;
  options: string[]; //only combobox has options. Textfield will be an empty array
  input_value: string;
  input_label: string; //gray text insidde input
  first_input: any; //only for double inputs or more
  second_input: any; //only for double inputs or more
  third_input: any; //only for double inputs or more
  fourth_input: any; //only for double inputs or more
  fifth_input: any; //only for double inputs or more
  sixth_input: any; //only for double inputs or more
  is_odd: number; // identifies side of input. 1== right column, 0== left column
  is_company: boolean; //if true show for companies, if false dont show for companies
  is_person: boolean; //if true show for natural persons, if false dont show for natural persons
  is_dependant: boolean; //if true show for dependant persons
  is_independant: boolean; //if true show for independant persons
}[] = [
  {
    key: "30",
    input_id: 0,
    input_type: 6, //0== textfield, 1 == combobox, 2==upload ,  3 == double input(combobox + textfield), 4===double download, 5=== triple download, 6===sixtuple download
    upper_text:
      "Adjunta tus Boletas de honorarios 6 meses o 6 últimos Formulario F29",
    options: [],
    input_value: "",
    input_label: "Tu nombre",
    is_odd: 0,
    first_input: {
      key: "130",
      input_id: 130,
      upper_text: "",
      input_value: "",
      input_label: "Carga documento 1",
    },
    second_input: {
      key: "131",
      input_id: 131,
      upper_text: "",
      input_value: "",
      input_label: "Carga documento 2",
    },
    third_input: {
      key: "132",
      input_id: 132,
      upper_text: "",
      input_value: "",
      input_label: "Carga documento 3",
    },
    fourth_input: {
      key: "133",
      input_id: 133,
      upper_text: "",
      input_value: "",
      input_label: "Carga documento 4",
    },
    fifth_input: {
      key: "134",
      input_id: 134,
      upper_text: "",
      input_value: "",
      input_label: "Carga documento 5",
    },
    sixth_input: {
      key: "135",
      input_id: 135,
      upper_text: "",
      input_value: "",
      input_label: "Carga documento 6",
    },
    is_company: false,
    is_person: true,
    is_dependant: false,
    is_independant: true,
  },
  {
    key: "31",
    input_id: 1,
    input_type: 2, //0== textfield, 1 == combobox, 2==upload ,  3 == double input(combobox + textfield), 4===double download, 5=== triple download, 6===sixtuple download
    upper_text: "Adjunta Fotocopia de RUT (si corresponde)",
    options: [],
    input_value: "",
    input_label: "Cargar documento",
    is_odd: 1,
    first_input: {},
    second_input: {},
    third_input: {},
    fourth_input: {},
    fifth_input: {},
    sixth_input: {},
    is_company: false,
    is_person: true,
    is_dependant: false,
    is_independant: true,
  },

  {
    key: "32",
    input_id: 2,
    input_type: 4, //0== textfield, 1 == combobox, 2==upload ,  3 == double input(combobox + textfield), 4===double download, 5=== triple download, 6===sixtuple download
    upper_text: "Adjunta 2 últimas declaraciones de impuesto a la renta (F22)",
    options: ["Si", "No"],
    input_value: "",
    input_label: "Apellido Paterno",
    is_odd: 1,
    first_input: {
      key: "136",
      input_id: 136,
      upper_text: "",
      input_value: "",
      input_label: "Carga documento 1",
    },
    second_input: {
      key: "137",
      input_id: 137,
      upper_text: "",
      input_value: "",
      input_label: "Carga documento 2",
    },
    third_input: {},
    fourth_input: {},
    fifth_input: {},
    sixth_input: {},
    is_company: false,
    is_person: true,
    is_dependant: false,
    is_independant: true,
  },

  {
    key: "39",
    input_id: 3,
    input_type: 5, //0== textfield, 1 == combobox, 2==upload ,  3 == double input(combobox + textfield), 4===double download, 5=== triple download, 6===sixtuple download
    upper_text: "Adjunta tus 3 últimas liquidaciones de sueldo",
    options: [],
    input_value: "",
    input_label: "Tu nombre",
    is_odd: 0,
    first_input: {
      key: "138",
      input_id: 138,
      upper_text: "",
      input_value: "",
      input_label: "Carga documento 1",
    },
    second_input: {
      key: "139",
      input_id: 139,
      upper_text: "",
      input_value: "",
      input_label: "Carga documento 2",
    },
    third_input: {
      key: "140",
      input_id: 140,
      upper_text: "",
      input_value: "",
      input_label: "Carga documento 3",
    },
    fourth_input: {},
    fifth_input: {},
    sixth_input: {},
    is_company: false,
    is_person: true,
    is_dependant: true,
    is_independant: false,
  },
  {
    key: "40",
    input_id: 4,
    input_type: 5, //0== textfield, 1 == combobox, 2==upload ,  3 == double input(combobox + textfield), 4===double download, 5=== triple download, 6===sixtuple download
    upper_text: "Adjunta tus 3 últimas cotizaciones obligatorias",
    options: [],
    input_value: "",
    input_label: "Tu nombre",
    is_odd: 1,
    first_input: {
      key: "141",
      input_id: 141,
      upper_text: "",
      input_value: "",
      input_label: "Carga documento 1",
    },
    second_input: {
      key: "142",
      input_id: 142,
      upper_text: "",
      input_value: "",
      input_label: "Carga documento 2",
    },
    third_input: {
      key: "143",
      input_id: 143,
      upper_text: "",
      input_value: "",
      input_label: "Carga documento 3",
    },
    fourth_input: {},
    fifth_input: {},
    sixth_input: {},
    is_company: false,
    is_person: true,
    is_dependant: true,
    is_independant: false,
  },
  {
    key: "41",
    input_id: 5,
    input_type: 2, //0== textfield, 1 == combobox, 2==upload ,  3 == double input(combobox + textfield), 4===double download, 5=== triple download, 6===sixtuple download
    upper_text: "Adjunta tu contrato de trabajo",
    options: [],
    input_value: "",
    input_label: "Cargar documento",
    is_odd: 0,
    first_input: {},
    second_input: {},
    third_input: {},
    fourth_input: {},
    fifth_input: {},
    sixth_input: {},
    is_company: false,
    is_person: true,
    is_dependant: true,
    is_independant: false,
  },

  {
    key: "42",
    input_id: 6,
    input_type: 2, //0== textfield, 1 == combobox, 2==upload ,  3 == double input(combobox + textfield), 4===double download, 5=== triple download, 6===sixtuple download
    upper_text: "Adjunta la Escritura de Constitución de la Sociedad",
    options: [],
    input_value: "",
    input_label: "Cargar documento",
    is_odd: 0,
    first_input: {},
    second_input: {},
    third_input: {},
    fourth_input: {},
    fifth_input: {},
    sixth_input: {},
    is_company: true,
    is_person: false,
    is_dependant: false,
    is_independant: false,
  },
  {
    key: "7",
    input_id: 43,
    input_type: 6, //0== textfield, 1 == combobox, 2==upload ,  3 == double input(combobox + textfield), 4===double download, 5=== triple download, 6===sixtuple download
    upper_text: "Adjunta Formulario 29 de los últimos 6 meses",
    options: [],
    input_value: "",
    input_label: "Tu nombre",
    is_odd: 1,
    first_input: {
      key: "144",
      input_id: 144,
      upper_text: "",
      input_value: "",
      input_label: "Carga documento 1",
    },
    second_input: {
      key: "145",
      input_id: 145,
      upper_text: "",
      input_value: "",
      input_label: "Carga documento 2",
    },
    third_input: {
      key: "146",
      input_id: 146,
      upper_text: "",
      input_value: "",
      input_label: "Carga documento 3",
    },
    fourth_input: {
      key: "147",
      input_id: 147,
      upper_text: "",
      input_value: "",
      input_label: "Carga documento 4",
    },
    fifth_input: {
      key: "148",
      input_id: 148,
      upper_text: "",
      input_value: "",
      input_label: "Carga documento 5",
    },
    sixth_input: {
      key: "149",
      input_id: 149,
      upper_text: "",
      input_value: "",
      input_label: "Carga documento 6",
    },
    is_company: true,
    is_person: false,
    is_dependant: false,
    is_independant: false,
  },
  {
    key: "44",
    input_id: 8,
    input_type: 2, //0== textfield, 1 == combobox, 2==upload ,  3 == double input(combobox + textfield), 4===double download, 5=== triple download, 6===sixtuple download
    upper_text: "Fotocopia del RUT",
    options: [],
    input_value: "",
    input_label: "Cargar documento",
    is_odd: 0,
    first_input: {},
    second_input: {},
    third_input: {},
    fourth_input: {},
    fifth_input: {},
    sixth_input: {},
    is_company: true,
    is_person: false,
    is_dependant: false,
    is_independant: false,
  },
  {
    key: "45",
    input_id: 9,
    input_type: 2, //0== textfield, 1 == combobox, 2==upload ,  3 == double input(combobox + textfield), 4===double download, 5=== triple download, 6===sixtuple download
    upper_text:
      "Escritura con poderes del Representante Legal para celebrar contratos de arriendo",
    options: [],
    input_value: "",
    input_label: "Cargar documento",
    is_odd: 0,
    first_input: {},
    second_input: {},
    third_input: {},
    fourth_input: {},
    fifth_input: {},
    sixth_input: {},
    is_company: true,
    is_person: false,
    is_dependant: false,
    is_independant: false,
  },
  {
    key: "46",
    input_id: 10,
    input_type: 2, //0== textfield, 1 == combobox, 2==upload ,  3 == double input(combobox + textfield), 4===double download, 5=== triple download, 6===sixtuple download
    upper_text: "Adjunta tu cédula de identidad frontal representante Legal",
    options: [],
    input_value: "",
    input_label: "Cargar documento",
    is_odd: 0,
    first_input: {},
    second_input: {},
    third_input: {},
    fourth_input: {},
    fifth_input: {},
    sixth_input: {},
    is_company: true,
    is_person: false,
    is_dependant: false,
    is_independant: false,
  },
  {
    key: "47",
    input_id: 11,
    input_type: 2, //0== textfield, 1 == combobox, 2==upload ,  3 == double input(combobox + textfield), 4===double download, 5=== triple download, 6===sixtuple download
    upper_text: "Adjunta tu cédula de identidad trasera representante Legal",
    options: [],
    input_value: "",
    input_label: "Cargar documento",
    is_odd: 0,
    first_input: {},
    second_input: {},
    third_input: {},
    fourth_input: {},
    fifth_input: {},
    sixth_input: {},
    is_company: true,
    is_person: false,
    is_dependant: false,
    is_independant: false,
  },
  {
    key: "48",
    input_id: 12,
    input_type: 2, //0== textfield, 1 == combobox, 2==upload ,  3 == double input(combobox + textfield), 4===double download, 5=== triple download, 6===sixtuple download
    upper_text: "Adjunta tu Carpeta Tributaria",
    options: [],
    input_value: "",
    input_label: "Cargar documento",
    is_odd: 1,
    first_input: {},
    second_input: {},
    third_input: {},
    fourth_input: {},
    fifth_input: {},
    sixth_input: {},
    is_company: true,
    is_person: false,
    is_dependant: false,
    is_independant: false,
  },
  {
    key: "49",
    input_id: 13,
    input_type: 2, //0== textfield, 1 == combobox, 2==upload ,  3 == double input(combobox + textfield), 4===double download, 5=== triple download, 6===sixtuple download
    upper_text: "Adjunta Certificado de Vigencia",
    options: [],
    input_value: "",
    input_label: "Cargar documento",
    is_odd: 1,
    first_input: {},
    second_input: {},
    third_input: {},
    fourth_input: {},
    fifth_input: {},
    sixth_input: {},
    is_company: true,
    is_person: false,
    is_dependant: false,
    is_independant: false,
  },
  {
    key: "50",
    input_id: 14,
    input_type: 2, //0== textfield, 1 == combobox, 2==upload ,  3 == double input(combobox + textfield), 4===double download, 5=== triple download, 6===sixtuple download
    upper_text:
      "Adjunta tu Delcaración de Renta (Formulario 22) del año anterior",
    options: [],
    input_value: "",
    input_label: "Cargar documento",
    is_odd: 0,
    first_input: {},
    second_input: {},
    third_input: {},
    fourth_input: {},
    fifth_input: {},
    sixth_input: {},
    is_company: true,
    is_person: false,
    is_dependant: false,
    is_independant: false,
  },
  {
    key: "51",
    input_id: 15,
    input_type: 2, //0== textfield, 1 == combobox, 2==upload ,  3 == double input(combobox + textfield), 4===double download, 5=== triple download, 6===sixtuple download
    upper_text: "Adjunta tu certificado de arriendos (Destacame o Equifax)",
    options: [],
    input_value: "",
    input_label: "Cargar documento",
    is_odd: 1,
    first_input: {},
    second_input: {},
    third_input: {},
    fourth_input: {},
    fifth_input: {},
    sixth_input: {},
    is_company: true,
    is_person: true,
    is_dependant: true,
    is_independant: true,
  },
  {
    key: "52",
    input_id: 16,
    input_type: 2, //0== textfield, 1 == combobox, 2==upload ,  3 == double input(combobox + textfield), 4===double download, 5=== triple download, 6===sixtuple download
    upper_text: "Adjunta tu cédula de identidad frontal",
    options: [],
    input_value: "",
    input_label: "Cargar documento",
    is_odd: 0,
    first_input: {},
    second_input: {},
    third_input: {},
    fourth_input: {},
    fifth_input: {},
    sixth_input: {},
    is_company: false,
    is_person: true,
    is_dependant: true,
    is_independant: true,
  },
  {
    key: "53",
    input_id: 17,
    input_type: 2, //0== textfield, 1 == combobox, 2==upload ,  3 == double input(combobox + textfield), 4===double download, 5=== triple download, 6===sixtuple download
    upper_text: "Adjunta tu cédula de identidad trasera",
    options: [],
    input_value: "",
    input_label: "Cargar documento",
    is_odd: 1,
    first_input: {},
    second_input: {},
    third_input: {},
    fourth_input: {},
    fifth_input: {},
    sixth_input: {},
    is_company: false,
    is_person: true,
    is_dependant: true,
    is_independant: true,
  },
];

export default step3InputsArray;
