import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function WhiteBackgroundWrapper({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section className="bg-[url(images/Backgrounds/WhiteBackground.png)] bg-[length:100%_100%]">
      {children}
    </section>
  );
}
