import { COMMUNES } from "@/constants/communes";
import { NATIONALITIES } from "@/constants/nationalities";
import { PROFESSIONS } from "@/constants/professions";

let step2InputsArray: step2InputInterface[] = [
  {
    key: "10",
    db_key: 'name',
    input_id: 0,
    input_type: 0, //0== textfield, 1 == combobox, 2==upload
    upper_text: "Nombre",
    options: [],
    input_value: "",
    input_label: "Tu nombre",
    first_input: {},
    second_input: {},
    is_company: false,
    is_person: true,
  },
  {
    key: "11",
    db_key: 'Company_legalRepresentativeName',
    input_id: 1,
    input_type: 0, //0== textfield, 1 == combobox, 2==upload
    upper_text: "Nombre Representante legal",
    options: [],
    input_value: "",
    input_label: "Nombre",
    first_input: {},
    second_input: {},
    is_company: true,
    is_person: false,
  },
  {
    key: "12",
    db_key: 'fatherLastName',
    input_id: 2,
    input_type: 0, //0== textfield, 1 == combobox, 2==upload
    upper_text: "Apellido Paterno",
    options: [],
    input_value: "",
    input_label: "Tu apellido Paterno",
    first_input: {},
    second_input: {},
    is_company: false,
    is_person: true,
  },
  {
    key: "13",
    db_key: 'Company_legalRepresentativeFatherLastName',
    input_id: 3,
    input_type: 0, //0== textfield, 1 == combobox, 2==upload
    upper_text: "Apellido Paterno Representante legal",
    options: ["Si", "No"],
    input_value: "",
    input_label: "Apellido Paterno",
    first_input: {},
    second_input: {},
    is_company: true,
    is_person: false,
  },
  {
    key: "14",
    db_key: 'motherLastName',
    input_id: 4,
    input_type: 0, //0== textfield, 1 == combobox, 2==upload
    upper_text: "Apellido Materno",
    options: [],
    input_value: "",
    input_label: "Tu Apellido Materno",
    first_input: {},
    second_input: {},
    is_company: false,
    is_person: true,
  },
  {
    key: "15",
    db_key: 'Company_legalRepresentativeMotherLastName',
    input_id: 5,
    input_type: 0, //0== textfield, 1 == combobox, 2==upload
    upper_text: "Apellido Materno Representante legal",
    options: [],
    input_value: "",
    input_label: "Apellido Materno",
    first_input: {},
    second_input: {},
    is_company: true,
    is_person: false,
  },
  {
    key: "16",
    db_key: 'rut',
    input_id: 6,
    input_type: 7, //0== textfield, 1 == combobox, 2==upload, 7 ===RUT
    upper_text: "RUT",
    options: [],
    input_value: "",
    input_label: "11.111.111-1",
    first_input: {},
    second_input: {},
    is_company: false,
    is_person: true,
  },
  {
    key: "17",
    db_key: 'Company_legalRepresentativeRut',
    input_id: 7,
    input_type: 7, //0== textfield, 1 == combobox, 2==upload
    upper_text: "RUT Representante legal",
    options: [],
    input_value: "",
    input_label: "11.111.111-1",
    first_input: {},
    second_input: {},
    is_company: true,
    is_person: false,
  },
  {
    key: "18",
    db_key: 'civilStatus',
    input_id: 8,
    input_type: 1, //0== textfield, 1 == combobox, 2==upload
    upper_text: "Estado civil",
    options: [
      "Soltero/a",
      "Casado/a",
      "Viudo/a",
      "Divorciado/a",
      "Conviviente civil",
    ],
    input_value: "",
    input_label: "Tu estado civil",
    first_input: {},
    second_input: {},
    is_company: false,
    is_person: true,
  },
  {
    key: "19",
    db_key: 'Company_rut',
    input_id: 9,
    input_type: 7, //0== textfield, 1 == combobox, 2==upload
    upper_text: "RUT Empresa",
    options: [],
    input_value: "",
    input_label: "11.111.111-1",
    first_input: {},
    second_input: {},
    is_company: true,
    is_person: false,
  },
  {
    key: "20",
    db_key: 'street',
    input_id: 10,
    input_type: 0, //0== textfield, 1 == combobox, 2==upload
    upper_text: "Calle y número",
    options: [],
    input_value: "",
    input_label: "Av. El Monasterio 1234 ",
    first_input: {},
    second_input: {},
    is_company: true,
    is_person: true,
  },
  {
    key: "21",
    db_key: 'commune',
    input_id: 11,
    input_type: 1, //0== textfield, 1 == combobox, 2==upload
    upper_text: "Comuna",
    options: COMMUNES,
    input_value: "",
    input_label: "Las condes",
    first_input: {},
    second_input: {},
    is_company: true,
    is_person: true,
  },
  {
    key: "22",
    db_key: 'phone',
    input_id: 12,
    input_type: 0, //0== textfield, 1 == combobox, 2==upload
    upper_text: "Celular",
    options: [],
    input_value: "",
    input_label: "+56 9 1234 5678",
    first_input: {},
    second_input: {},
    is_company: true,
    is_person: true,
  },
  {
    key: "23",
    db_key: 'nationality',
    input_id: 13,
    input_type: 1, //0== textfield, 1 == combobox, 2==upload
    upper_text: "Nacionalidad",
    options: NATIONALITIES,
    input_value: "",
    input_label: "Chileno",
    first_input: {},
    second_input: {},
    is_company: false,
    is_person: true,
  },
  {
    key: "24",
    db_key: 'profession',
    input_id: 14,
    input_type: 1, //0== textfield, 1 == combobox, 2==upload
    upper_text: "Profesion",
    options: PROFESSIONS,
    input_value: "",
    input_label: "Diseñador",
    first_input: {},
    second_input: {},
    is_company: false,
    is_person: true,
  },
  {
    key: "25",
    db_key: 'workerType',
    input_id: 15,
    input_type: 1, //0== textfield, 1 == combobox, 2==upload
    upper_text: "Tipo de trabajo",
    options: ["Dependiente", "Independiente"],
    input_value: "",
    input_label: "Dependiente",
    first_input: {},
    second_input: {},
    is_company: false,
    is_person: true,
  },
];

export default step2InputsArray;
