export const COMMUNES = [
  "Aisén",
  "Algarrobo",
  "Alhué",
  "Alto Biobío",
  "Alto del Carmen",
  "Alto Hospicio",
  "Ancud",
  "Andacollo",
  "Angol",
  "Antártica",
  "Antofagasta",
  "Antuco",
  "Arauco",
  "Arica",
  "Buin",
  "Bulnes",
  "Cabildo",
  "Cabo de Hornos (Ex Navarino)",
  "Calama",
  "Calbuco",
  "Caldera",
  "Calera",
  "Calera de Tango",
  "Calle Larga",
  "Camarones",
  "Camiña",
  "Canela",
  "Cañete",
  "Carahue",
  "Cartagena",
  "Casablanca",
  "Castro",
  "Catemu",
  "Cauquenes",
  "Cerrillos",
  "Cerro Navia",
  "Chaitén",
  "Chanco",
  "Chañaral",
  "Chépica",
  "Chiguayante",
  "Chile Chico",
  "Chillán",
  "Chillán Viejo",
  "Chimbarongo",
  "Cholchol",
  "Cochamó",
  "Codegua",
  "Coelemu",
  "Coihaique",
  "Coihueco",
  "Colbún",
  "Colchane",
  "Colina",
  "Coltauco",
  "Combarbalá",
  "Concepción",
  "Concón",
  "Conchalí",
  "Constitución",
  "Contulmo",
  "Copiapó",
  "Coronel",
  "Corral",
  "Cochrane",
  "Cisnes",
  "Cunco",
  "Curanilahue",
  "Curacautín",
  "Curacaví",
  "Curaco de Vélez",
  "Curarrehue",
  "Curepto",
  "Curicó",
  "Dalcahue",
  "Diego de Almagro",
  "Doñihue",
  "El Bosque",
  "El Carmen",
  "El Monte",
  "El Quisco",
  "El Tabo",
  "Empedrado",
  "Ercilla",
  "Estación Central",
  "Florida",
  "Freire",
  "Freirina",
  "Fresia",
  "Frutillar",
  "Futrono",
  "Galvarino",
  "General Lagos",
  "Gorbea",
  "Graneros",
  "Guaitecas",
  "Hijuelas",
  "Hualaihué",
  "Hualañé",
  "Hualpén",
  "Hualqui",
  "Huara",
  "Huechuraba",
  "Huasco",
  "Illapel",
  "Independencia",
  "Iquique",
  "Isla de Maipo",
  "Isla de Pascua",
  "Juan Fernández",
  "La Cisterna",
  "La Estrella",
  "La Florida",
  "La Granja",
  "La Higuera",
  "La Ligua",
  "La Pintana",
  "La Reina",
  "La Serena",
  "Lago Ranco",
  "Lago Verde",
  "Laja",
  "Lampa",
  "Lanco",
  "Las Cabras",
  "Las Condes",
  "Lautaro",
  "Lebu",
  "Licantén",
  "Limache",
  "Linares",
  "Litueche",
  "Llanquihue",
  "Llaillay",
  "Lolol",
  "Loncoche",
  "Longaví",
  "Lonquimay",
  "Los Álamos",
  "Los Andes",
  "Los Ángeles",
  "Los Lagos",
  "Los Muermos",
  "Los Sauces",
  "Los Vilos",
  "Lumaco",
  "Macul",
  "Machalí",
  "Maipú",
  "Malloa",
  "Mariquina",
  "María Elena",
  "María Pinto",
  "Marchihue",
  "Máfil",
  "Maullín",
  "Mejillones",
  "Melipeuco",
  "Melipilla",
  "Monte Patria",
  "Mostazal",
  "Mulchén",
  "Nacimiento",
  "Nancagua",
  "Natales",
  "Navidad",
  "Negrete",
  "Ninhue",
  "Nogales",
  "Nueva Imperial",
  "Ñiquén",
  "Ñuñoa",
  "O’Higgins",
  "Ollagüe",
  "Olmué",
  "Olivar",
  "Ovalle",
  "Padre las Casas",
  "Padre Hurtado",
  "Paiguano",
  "Paillaco",
  "Paine",
  "Palmilla",
  "Panquehue",
  "Panguipulli",
  "Papudo",
  "Paredones",
  "Pedro Aguirre Cerda",
  "Pelarco",
  "Pelluhue",
  "Pemuco",
  "Peñaflor",
  "Peñalolén",
  "Pencahue",
  "Penco",
  "Peralillo",
  "Perquenco",
  "Petorca",
  "Peumo",
  "Pica",
  "Pichidegua",
  "Pichilemu",
  "Pinto",
  "Pirque",
  "Placilla",
  "Porvenir",
  "Portezuelo",
  "Pozo Almonte",
  "Primavera",
  "Providencia",
  "Puchuncaví",
  "Pucón",
  "Pudahuel",
  "Puente Alto",
  "Puerto Montt",
  "Puerto Octay",
  "Puerto Varas",
  "Pumanque",
  "Punta Arenas",
  "Puno",
  "Pupuya",
  "Purranque",
  "Puyehue",
  "Putre",
  "Putaendo",
  "Puqueldón",
  "Quellón",
  "Quemchi",
  "Queilén",
  "Quilaco",
  "Quilicura",
  "Quilleco",
  "Quillota",
  "Quillón",
  "Quilpué",
  "Quinchao",
  "Quinta de Tilcoco",
  "Quinta Normal",
  "Quintero",
  "Quirihue",
  "Rancagua",
  "Ránquil",
  "Rauco",
  "Recoleta",
  "Renaico",
  "Renca",
  "Rengo",
  "Requínoa",
  "Retiro",
  "Río Bueno",
  "Río Claro",
  "Río Hurtado",
  "Río Ibáñez",
  "Río Negro",
  "Río Verde",
  "Romeral",
  "Saavedra",
  "Sagrada Familia",
  "Salamanca",
  "San Antonio",
  "San Bernardo",
  "San Carlos",
  "San Clemente",
  "San Esteban",
  "San Fabián",
  "San Felipe",
  "San Fernando",
  "San Gregorio",
  "San Ignacio",
  "San Javier",
  "San Joaquín",
  "San José de Maipo",
  "San Juan de la Costa",
  "San Miguel",
  "San Nicolás",
  "San Pablo",
  "San Pedro",
  "San Pedro de Atacama",
  "San Pedro de la Paz",
  "San Pedro de Maipo",
  "San Rafael",
  "San Ramón",
  "San Rosendo",
  "San Vicente",
  "Santa Bárbara",
  "Santa Cruz",
  "Santa Juana",
  "Santa María",
  "Santiago",
  "Santo Domingo",
  "Sierra Gorda",
  "Talagante",
  "Talcahuano",
  "Taltal",
  "Talca",
  "Temuco",
  "Teno",
  "Teodoro Schmidt",
  "Tierra Amarilla",
  "Tiltil",
  "Timaukel",
  "Tirúa",
  "Tocopilla",
  "Toltén",
  "Tomé",
  "Torres del Paine",
  "Traiguén",
  "Treguaco",
  "Tucapel",
  "Valdivia",
  "Vallenar",
  "Valparaíso",
  "Victoria",
  "Vichuquén",
  "Vilcún",
  "Villa Alegre",
  "Villa Alemana",
  "Villarrica",
  "Viña del Mar",
  "Vitacura",
  "Yerbas Buenas",
  "Yumbel",
  "Yungay",
  "Zapallar",
]
