export const PROFESSIONS = [
  "Ingeniería en Administración de Recursos Humanos y similares",
  "Técnico en Administración de Recursos Humanos",
  "Agronomía",
  "Ingeniería Agrícola y Agropecuaría",
  "Ingeniería Agroindustrial",
  "Ingeniería Agronómica",
  "Ingeniería Civil Agroindustrial y similares",
  "Ingeniería Civil en Industrias de la Madera",
  "Ingeniería en Acuicultura y similares",
  "Ingeniería en Alimentos y similares",
  "Ingeniería Forestal y similares",
  "Técnico Agropecuario y similares",
  "Técnico en Acuicultura y similares",
  "Técnico en Alimentos y similares",
  "Técnico en Madera",
  "Bachillerato en Humanidades",
  "Bibliotecología",
  "Literatura y/o letras",
  "Periodismo y similares",
  "Técnico en Bibliotecología",
  "Técnico en Traducción, Interpretación y similares",
  "Traducción, Intérprete y similares",
  "Actuación y similares",
  "Arte y similares",
  "Composición, interpretación musical y similares",
  "Danza",
  "Música, Licenciatura en música",
  "Técnico en Artes Escénicas",
  "Animación digital y similares",
  "Cine y Televisión",
  "Comunicación Audiovisual, Digital y similares",
  "Dibujante Proyectista y similares",
  "Diseño",
  "Diseño de Interiores y similares",
  "Diseño de Vestuario",
  "Diseño Gráfico, Diseño Web y similares",
  "Diseño Industrial y similares",
  "Fotografía Profesional y similares",
  "Paisajismo y similares",
  "Técnico en Animación digital",
  "Técnico en Artes y similares",
  "Técnico en Comunicación Audiovisual y similares",
  "Técnico en Dibujo Arquitectónico, Dibujo Técnico y similares",
  "Técnico en Dirección y Producción de Eventos",
  "Técnico en Diseño Ambientes",
  "Técnico en Diseño de Vestuario",
  "Técnico en Diseño Gráfico y similares",
  "Técnico en Diseño Web y similares",
  "Técnico en Diseño, Ilustración y similares",
  "Técnico en Fotografía",
  "Técnico en Paisajismo",
  "Técnico en Restauración y similares",
  "Bachillerato en Ciencias y similares",
  "Bioingeniería",
  "Biología",
  "Biología Marina y similares",
  "Bioquímica",
  "Física, Astronomía y similares",
  "Geología",
  "Ingeniería Ambiental",
  "Ingeniería Civil Ambiental",
  "Ingeniería Civil en Biotecnología y similares",
  "Ingeniería en Biotecnología y similares",
  "Ingeniería en Geomensura y similares",
  "Ingeniería Química y similares",
  "Licenciatura en Ciencias y similares",
  "Química y carreras similares",
  "Técnico en Energías Renovables",
  "Técnico en Geología",
  "Técnico en Química, Análisis Químico y similares",
  "Técnico en Topografía",
  "Técnico en Vitivinicultura",
  "Antropología, Arqueología y similares",
  "Bachillerato en Ciencias Sociales y similares",
  "Ciencias Políticas y similares",
  "Filosofía",
  "Geografía",
  "Historia",
  "Psicología",
  "Sociología",
  "Teología",
  "Construcción Civil",
  "Ingeniería Civil en Obras Civiles y similares",
  "Ingeniería en Construcción y similares",
  "Ingeniería en Mantenimiento Industrial y similares",
  "Técnico en Construcción",
  "Técnico en Instalaciones Sanitarias y similares",
  "Técnico en Obras Civiles y similares",
  "Entrenador Profesional y similares",
  "Bachillerato en Ciencias de la Salud",
  "Enfermería",
  "Fonoaudiología",
  "Kinesiología",
  "Medicina",
  "Medicina Veterinaria",
  "Medicinas Alternativas",
  "Obstetricia y Puericultura",
  "Odontología",
  "Técnico en Fisioterapia, Kinesiología y similares",
  "Técnico en Medicinas Alternativas",
  "Técnico en Obstetricia y Puericultura",
  "Técnico en Odontología, Asistente Dental y similares",
  "Técnico en Veterinaria",
  "Terapia Ocupacional",
  "Ingeniería en Logística y similares",
  "Técnico en Logística y similares",
  "Educación Diferencial",
  "Educación Parvularia",
  "Pedagogía Básica y menciones",
  "Pedagogía en Artes",
  "Pedagogía en Biología, Química y similares",
  "Pedagogía en Castellano y similares",
  "Pedagogía en Educación Física y similares",
  "Pedagogía en Filosofía",
  "Pedagogía en Física",
  "Pedagogía en Historia y Geografía",
  "Pedagogía en Inglés y similares",
  "Pedagogía en Matemáticas",
  "Pedagogía en Música",
  "Pedagogía en Religión",
  "Pedagogía, Licenciatura en Educación y similares",
  "Psicopedagogía",
  "Técnico Educacional y similares",
  "Técnico en Educación Especial y/o Diferencial y similares",
  "Técnico en Educación Parvularia",
  "Ingeniería Civil en Computación y/o Informática",
  "Ingeniería en Computación e Informática y similares",
  "Ingeniería en Conectividad y Redes",
  "Técnico en Administración de Redes Computacionales",
  "Técnico en Análisis de Sistemas Informáticos",
  "Técnico en Computación e Informática",
  "Ingeniería Civil Eléctrica y similares",
  "Ingeniería Civil Mecánica",
  "Ingeniería Eléctrica y similares",
  "Ingeniería Electrónica y similares",
  "Ingeniería en Climatización, Refrigeración y similares",
  "Ingeniería en Mecánica Automotriz",
  "Técnico en Electricidad, Electrónica y similares",
  "Técnico en Mecánica Automotriz",
  "Técnico en Mecánica Industrial, mantención y similares",
  "Técnico en Refrigeración, Climatización y similares",
  "Producción de Eventos y similares",
  "Técnico en Administración de Empresas",
  "Técnico en Administración Pública",
  "Técnico en Comercio Exterior",
  "Técnico en Marketing",
  "Técnico en Producción de Eventos",
  "Técnico en Relaciones Públicas",
  "Administración de Empresas y/o Negocios Internacionales",
  "Administración Pública",
  "Contador Auditor",
  "Contador Público y/o General",
  "Ingeniería Comercial",
  "Ingeniería en Marketing y/o Comercial",
  "Relaciones Públicas",
  "Técnico Financiero",
  "Economía",
  "Técnico en Administración de Redes e infraestructura",
  "Técnico en Telecomunicaciones",
  "Ingeniería en Telecomunicaciones, Conectividad y Redes",
  "Trabajo Social",
  "Técnico en Trabajo Social",
  "Ingeniería Civil Industrial",
  "Ingeniería Industrial",
  "Técnico Industrial",
  "Derecho",
  "Técnico Jurídico y similares",
  "Ingeniería Civil en Minas",
  "Ingeniería en Minas",
  "Técnico en Minería y similares",
  "Ingeniería Civil en Metalurgia y/o Materiales y similares",
  "Ingeniería en Metalurgia y similares",
  "Técnico en Metalurgia",
  "Cartografía",
  "Diseño de Productos Multimedia",
  "Ingeniería en Prevensión de Riesgos",
  "Técnico en Diseño de Productos Multimedia",
  "Técnico en Prevención de Riesgos",
  "Técnico en Sonido y similares",
  "Técnico en Turismo",
  "Turismo, Hotelería y similares",
  "Otro",
]
