let step1InputsArray: step1InputInterface[] = [
  {
    key: "0",
    db_key: "broker",
    input_id: 0,
    input_type: 0, //0== textfield, 1 == combobox, 2==upload
    upper_text:
      "Nombre de la corredora, empresa o persona que recibe tu información",
    options: [],
    input_value: "",
    input_label: "S&J Propiedades",
    first_input: {},
    second_input: {},
    is_company: true,
    is_person: true,
    is_email: false,
  },
  {
    key: "1",
    db_key: "brokerEmail",
    input_id: 1,
    input_type: 0, //0== textfield, 1 == combobox, 2==upload
    upper_text: "Correo al cual se envía el link de acceso",
    options: [],
    input_value: "",
    input_label: "documentos@propiedadessyj.com",
    first_input: {},
    second_input: {},
    is_company: true,
    is_person: true,
    is_email: true,
  },
  {
    key: "2",
    db_key: "linkTime",
    input_id: 2,
    input_type: 1, //0== textfield, 1 == combobox, 2==upload
    upper_text: "Plazo para acceder a la información",
    options: ["1 día", "1 semana", "1 mes"],
    input_value: "",
    input_label: "Selecciona el plazo",
    first_input: {},
    second_input: {},
    is_company: true,
    is_person: true,
    is_email: false,
  },
  {
    key: "3",
    db_key: "needCosigner",
    input_id: 3,
    input_type: 1, //0== textfield, 1 == combobox, 2==upload
    upper_text: "¿Necesitarás aval?",
    options: ["Si", "No"],
    input_value: "",
    input_label: "Si/No",
    first_input: {},
    second_input: {},
    is_company: true,
    is_person: true,
    is_email: false,
  },
  {
    key: "4",
    db_key: "isCosigner",
    input_id: 4,
    input_type: 3, //0== textfield, 1 == combobox, 2==upload
    upper_text: "¿Eres aval de otra postulación?",
    options: [],
    input_value: "",
    input_label: "",
    first_input: {
      key: "104",
      input_id: 104,
      upper_text: "",
      options: ["Si", "No"],
      input_value: "",
      input_label: "Si/No",
    },
    second_input: {
      key: "105",
      db_key: "cosignerApplicationId",
      input_id: 105,
      input_type: 1, //0== textfield, 1 == combobox, 2==upload
      upper_text: "",
      options: [],
      input_value: "",
      input_label: "Código de postulación",
    },
    is_company: true,
    is_person: true,
    is_email: false,
  },
  {
    key: "5",
    db_key: "type",
    input_id: 5,
    input_type: 1, //0== textfield, 1 == combobox, 2==upload
    upper_text: "Postulas como",
    options: ["Empresa", "Persona Natural"],
    input_value: "",
    input_label: "Selecciona el plazo",
    first_input: {},
    second_input: {},
    is_company: true,
    is_person: true,
    is_email: false,
  },
];

export default step1InputsArray;
