import type { Metadata } from "next";
import { Inter } from "next/font/google";
import GreenBackgroundWrapper from "../../Components/Wrappers/GreenBackgroundWrapper";
import { LayoutWrapperComponent } from "@/Components/Wrappers/layout-wrapper.component";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <LayoutWrapperComponent><GreenBackgroundWrapper>{children}</GreenBackgroundWrapper></LayoutWrapperComponent>;
}
